### ISSUE TITLE
[DataCap Application] Smithsonian Open Access

### ISSUE THREAD

**Issue by JackFsy** [filecoin-project/filecoin-plus-large-datasets#391]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: BigData Exchange
- Website / Social Media: www.bigd.exchange / https://twitter.com/BigD_Exchange
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3.24PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 300TiB
- On-chain address for first allocation: f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
BigData Exchange is a Filecoin data storage marketplace that connects clients with valuable public data and storage providers with storage capacity. Headquartered and operated in Singapore, there are currently over 30 people globally in the core team.
With the current demand for Filecoin plus deals, there are several benefits that BigData Exchange brings to the Filecoin network:

- An innovative storage platform to incentivize more people to source, migrate, and store valuable public data on Filecoin
- A transparent marketplace to connect Fil+ clients and storage providers, which adds visibility to the SP selection process and prevents potential self-dealing activities
- An index of public data stored on Filecoin, which paves the way to a vibrant retrieval and service market for Fil+ deals

The goal is not to profit from DataCap. For any proceeds, we will donate them to data preservation organization or use them to fund/incentivize activities that aim to onboard more useful data storage on Filecoin.
```

What is the primary source of funding for this project?
```
The project is self funded.
```

What other projects/ecosystem stakeholders is this project associated with?
```
The project is self funded.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Smithsonian Open Access is a public open dataset available in AWS S3. The Smithsonian’s mission is the "increase and diffusion of knowledge" and has been collecting since 1846. The Smithsonian, through its efforts to digitize its multidisciplinary collections, has created millions of digital assets and related metadata describing the collection objects.
```

Where was the data in this dataset sourced from?
```
On February 25th, 2020, the Smithsonian released over 2.8 million CC0 interdisciplinary 2-D and 3-D images, related metadata, and additionally, research data from researches across the Smithsonian. The 2.8 million "open access" collections are a subset of the Smithsonian’s 155 million objects, 2.1 million library volumes and 156,000 cubic feet of archival collections held in 19 museums, 9 research centers, libraries, archives and the National Zoo. Digitization of collections is ongoing.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
[Please answer here.](https://registry.opendata.aws/smithsonian-open-access/)
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes
```

What is the expected retrieval frequency for this data?
```
It will serve as a public data copy on the decentralized web that is open for anybody’s access. The retrieval frequency for this data will depend on user demand.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
18 months
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We do not have regional preference currently, but our ideal goal would be to make sure that users from all over the world can access this valuable open data.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We will provide an online URL for the storage providers to download CAR files.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will list the dataset described above on BigData Exchange and await bids from storage providers. Once the auction period ends, we will check SP’s bidding price, reputation, geographic information, sealing speed, etc. to select the final storage providers to work with.
```

How will you be distributing deals across storage providers?
```
The dataset will have 3 replicas and we are planning to distribute them to different storage providers with up to 20% each.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
We will use BigData Exchange to find the right storage providers. For each allocation, we will create auctions with an auction period to be 7 days. When the auction ends, we will be ready to make deals with storage providers directly. The goal is not to profit from DataCap. For any proceeds, we will donate them to data preservation organization or use them to fund/incentivize activities that aim to onboard more useful data storage on Filecoin.
```

**Comment by Yvette516** [comment]
How would you make deals with SP online?

**Comment by JackFsy** [comment]
Hey @Yvette516 , we will be proposing offline deals with SPs. The process works as below:
1. Prepare CAR files and upload to an online server
2. SPs download CAR files from the provided URL 
3. Propose offline deal to SP once they have files ready to import.

**Comment by Sunnyiscoming** [comment]
@JackFsy  Hey. Could you send an email to filplus@fil.org with your official domain in order to confirm your identity?

**Comment by JackFsy** [comment]
> @JackFsy Hey. Could you send an email to [filplus@fil.org](mailto:filplus@fil.org) with your official domain in order to confirm your identity?

Hey @Sunnyiscoming , sent. Thanks

**Comment by JackFsy** [comment]
> I support this LDN. Similarly to Estuary and FilSwan, utility based LDNs are worth consideration.

Hi @kernelogic , thank you for your support!

**Comment by cryptowhizzard** [comment]
Hi there,

Today in the governance call there were some slides , including a slide stating that the revenue of this project would be donated. Can you put those slides here in this request @JackFsy ?

From what i understand is that @kernelogic ( Techgreedy ) and Xinan will build and distribute this dataset for you. Is that right? 

If i understand correct on both then i will support this application.

**Comment by swatchliu** [comment]
I support this LDN.  

100% match with LDN's demand. A Public Dataset Hub is easier for SP to find data and apply for DC.

**Comment by JackFsy** [comment]
> I talked to the team at Austin. I can support this LDN application.

Hey @Fenbushi-Filecoin , thank you for your support!

**Comment by JackFsy** [comment]
> Hi there,
> 
> Today in the governance call there were some slides , including a slide stating that the revenue of this dataset would be donated. Can you put those slides here in this request @JackFsy ?
> 
> From what i understand is that @kernelogic ( Techgreedy ) and Xinan will build and distribute this dataset for you. Is that right?
> 
> If i understand correct on both then i will support this application.

Hey @cryptowhizzard ,

Yes, we will work will XinAn to prepare the data. As per requested, our one-page slide is attached below.
![image](https://user-images.githubusercontent.com/104066174/176577380-476d27de-782d-4c45-8dec-1c663794abae.png)

Thank you for your support!

**Comment by JackFsy** [comment]
> I support this LDN.
> 
> 100% match with LDN's demand. A Public Dataset Hub is easier for SP to find data and apply for DC.

Hey @swatchliu , Thank you for your support!

**Comment by Sunnyiscoming** [comment]
@JackFsy Hey. Could you send an email to [filplus@fil.org](mailto:filplus@fil.org) with your official domain in order to confirm your identity?

**Comment by JackFsy** [comment]
> @JackFsy Hey. Could you send an email to [filplus@fil.org](mailto:filplus@fil.org) with your official domain in order to confirm your identity?

Hey @Sunnyiscoming , already sent with subject: [DataCap Application] Smithsonian Open Access #391

**Comment by JackFsy** [comment]
Hey @galen-mcandrew , are we able to have this application approved?

**Comment by cbtan21** [comment]
@Sunnyiscoming @galen-mcandrew Hi Team, may I request for an update on the status of this application? Is it currently being reviewed or is there a blocker to this application? We have 4 notaries that approve of our application. Thank you for your help and time.

**Comment by MetaWaveInfo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaxd5kxsd3qy4k2ambzhg3q3pmsufbqiiiipavckd6cxmyu45q6a4 
#### Address 
> f1cknbfzj656hmk6hqrblzs24ecv6ndg5pmxt5aka
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaxd5kxsd3qy4k2ambzhg3q3pmsufbqiiiipavckd6cxmyu45q6a4

**Comment by JackFsy** [comment]
Hi all notaries and community members (cc @dkkapur), we would like to raise a request to remove the previously allocated DataCap in **f1cknbfzj656hmk6hqrblzs24ecv6ndg5pmxt5aka** as we are having issues using this wallet address for deal making. Could you please help us to remove it and allocate the same amount to **f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi**?
Going forward, we will also be using this wallet address **f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi** for our existing LDN application #391. Please advise if that is okay too.
Sorry for the inconvenience caused and thank you very much for your help!

**Comment by dkkapur** [comment]
Hey folks - going to recommend that we do the following here:

- tooling is still WIP for removing DataCap from client addresses
- this address cannot be used for deal making so we don't have risk here with DataCap being abused
- notaries agreed to give DataCap to this project previously, so should support giving it to a new address immediately
- based on this, going to kick off a new request to get DataCap at the new wallet address to unblock the project and move the old address into the list of testing addresses for DataCap removal cc @raghavrmadya @galen-mcandrew as part of tooling being built

**Comment by dkkapur** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f01858410

#### Client address
> f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi

#### DataCap allocation requested
> 150TiB

**Comment by dkkapur** [comment]
@kernelogic @MetaWaveInfo as notaries that signed the first request, paging you here to see if you can sign this one as well. Thank you.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5k7xnzvjdc4hkiyri65irjzkte6lupkurcqsmppsq47637kha4e 
#### Address 
> f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5k7xnzvjdc4hkiyri65irjzkte6lupkurcqsmppsq47637kha4e

**Comment by kernelogic** [comment]
Done! Talking about TTD!

**Comment by newwebgroup** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceazjvg4tuuccrlixzmm46oz77bwieyxnhjl2rhybcwy7c24yusrl4 
#### Address 
> f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi
#### Datacap Allocated
> 150.00TiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceazjvg4tuuccrlixzmm46oz77bwieyxnhjl2rhybcwy7c24yusrl4

**Comment by JackFsy** [comment]
Hey @dkkapur @raghavrmadya , we have used more than 75% of DataCap but the bot for next tranche is not triggered. Could you please help us check what's wrong here?

**Comment by dkkapur** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f01858410

#### Client address
> f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi

#### DataCap allocation requested
> 300TiB

**Comment by dkkapur** [comment]
Requesting manually. Pretty sure it's because the parent comment / issue still has original address on it. Waiting on tech team confirmation before editing and overriding.

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebxvz5kjmqyrbuiqxn2l72t53mtja2hes7sqh2x2g2bwobkeffy6q 
#### Address 
> f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebxvz5kjmqyrbuiqxn2l72t53mtja2hes7sqh2x2g2bwobkeffy6q

**Comment by xinaxu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4wfewnunqbllcgdv6he5fgqwkbsikjq4k7vvmeoolokeaexz4zm 
#### Address 
> f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi
#### Datacap Allocated
> 300.00TiB
#### Signer Address
> f1k3ysofkrrmqcot6fkx4wnezpczlltpirmrpsgui
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4wfewnunqbllcgdv6he5fgqwkbsikjq4k7vvmeoolokeaexz4zm

**Comment by dkkapur** [comment]
## DataCap Allocation requested

#### Multisig Notary address
> f01858410

#### Client address
> f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi

#### DataCap allocation requested
> 600TiB

**Comment by 1ane-1** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceapxlnodgwpdf2l6wb3ckwj2nqhxv4dni6h7ebyisdc7jzbyzq4mo 
#### Address 
> f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceapxlnodgwpdf2l6wb3ckwj2nqhxv4dni6h7ebyisdc7jzbyzq4mo

**Comment by stcouldlisa** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebopv7t5nzx76v34ecvkvih5r5rh5ws7u7gxlyq73ituktpmbzmyq 
#### Address 
> f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi
#### Datacap Allocated
> 600.00TiB
#### Signer Address
> f1jvvltduw35u6inn5tr4nfualyd42bh3vjtylgci
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebopv7t5nzx76v34ecvkvih5r5rh5ws7u7gxlyq73ituktpmbzmyq

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatumn7p2ixnienegkyocpmr2idhpxboqnv5mjwd7ntlj6qaytqfe 
#### Address 
> f1cknbfzj656hmk6hqrblzs24ecv6ndg5pmxt5aka
#### Datacap Allocated
> 2.06PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatumn7p2ixnienegkyocpmr2idhpxboqnv5mjwd7ntlj6qaytqfe

**Comment by liyunzhi-666** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdrjkjanxn2j2yb6qcqd7wzohf4ki25pg2p2yaczc2ql6aljvx4m 
#### Address 
> f1cknbfzj656hmk6hqrblzs24ecv6ndg5pmxt5aka
#### Datacap Allocated
> 2.06PiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdrjkjanxn2j2yb6qcqd7wzohf4ki25pg2p2yaczc2ql6aljvx4m

**Comment by kernelogic** [comment]
Looks like this LDN changed address after it's approved but the bot still triggering top ups on both addresses. Need to de-allocate the old address when the feature is available. @dkkapur

**Comment by raghavrmadya** [comment]
## DataCap Allocation requested

### Request number 6
#### Multisig Notary address
> f01858410

#### Client address
> f1cknbfzj656hmk6hqrblzs24ecv6ndg5pmxt5aka

#### DataCap allocation requested
> 1.2PiB

**Comment by raghavrmadya** [comment]
## DataCap Allocation requested

### Request number 6
#### Multisig Notary address
> f01858410

#### Client address
> f1cknbfzj656hmk6hqrblzs24ecv6ndg5pmxt5aka

#### DataCap allocation requested
> 1.2PiB

**Comment by raghavrmadya** [comment]
Manually triggering request 6 due to address the change issue pointed out above. We are aware of DC being allocated to the previous address and are keeping a close eye on the usage of DC to the old address. W will remove DC from that address once the tooling to do so is shipped

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceddqdd7qlp73oc7uvhpt4lndh4sauxsjju5ofgs557g6pfyhwtuvg 
#### Address 
> f1cknbfzj656hmk6hqrblzs24ecv6ndg5pmxt5aka
#### Datacap Allocated
> 1.20PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceddqdd7qlp73oc7uvhpt4lndh4sauxsjju5ofgs557g6pfyhwtuvg

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkzpd3jpdt35isses7mvabk45t55wndqdz2v4meop2i7azxrac5e 
#### Address 
> f1cknbfzj656hmk6hqrblzs24ecv6ndg5pmxt5aka
#### Datacap Allocated
> 1.20PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkzpd3jpdt35isses7mvabk45t55wndqdz2v4meop2i7azxrac5e

**Comment by JackFsy** [comment]
Hi @raghavrmadya , sorry that the manual trigger above was to the wrong address again... Our Filecoin address is f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi which is used to receive DataCap.

**Comment by raghavrmadya** [comment]
## DataCap Allocation requested

### Request number 6
#### Multisig Notary address
> f01858410

#### Client address
> f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi

#### DataCap allocation requested
> 1.2PiB

**Comment by raghavrmadya** [comment]
The last trigger was to the incorrect address. It is being monitored to prevent any abuse. notaries are requested to please sign again

**Comment by newwebgroup** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxbqvfp3mxwnzhptxqivw7gl6i7dnayf5nfji5umzwx3iljjbxh4 
#### Address 
> f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi
#### Datacap Allocated
> 1.20PiB
#### Signer Address
> f1e77zuityhvvw6u2t6tb5qlnsegy2s67qs4lbbbq
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxbqvfp3mxwnzhptxqivw7gl6i7dnayf5nfji5umzwx3iljjbxh4

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedp4kauzb5t4sntv4e5ki6ieoun5fzjsl66jjk4t3qaoknutsrsxq 
#### Address 
> f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi
#### Datacap Allocated
> 1.20PiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedp4kauzb5t4sntv4e5ki6ieoun5fzjsl66jjk4t3qaoknutsrsxq

**Comment by lvschouwen** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
checker:manualTrigger

**Comment by JackFsy** [comment]
Hi @dkkapur @raghavrmadya, we have utilized more than 95% of the previous allocation but the bot is not triggered yet probably due to the change of wallet address before. Can we trouble you to manually trigger the bot for the last tranche? Our wallet address is: f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi. Understanding the CID checker result is not showing. Probably this is due to the change of wallet as well.

**Comment by dkkapur** [comment]
@JackFsy - interesting bug on the CID checker front, probs requires a patch cc @brossetti1 @xinaxu 

Looks like just 19GB left on this, triggering next manually.

**Comment by dkkapur** [comment]
## DataCap Allocation requested

### Request number 7
#### Multisig Notary address
> f01858410

#### Client address
> f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi

#### DataCap allocation requested
> 1.2PiB

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by dkkapur** [comment]
<img width="954" alt="Screen Shot 2023-02-01 at 12 45 25 AM" src="https://user-images.githubusercontent.com/2343218/215994040-ce8ebe9d-e8db-4061-b75c-039d290062c3.png">


@cryptowhizzard  I definitely see deals on chain. Maybe its an attribute of the deals themselves, i.e., start epochs in the future, or something about how we're scraping on the CID checker front? cc @xinaxu @brossetti1

**Comment by dkkapur** [comment]
overriding it.

**Comment by dkkapur** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
#391 is still not visible in our Fil+ dash.

**Comment by dkkapur** [comment]
@panges2 @fabriziogianni7 labels look right to me. what's missing?

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedyvkp2wxekl77dpdnyto6jylwp7ilr6a3qo7mobmnosm2o2xmksq 
#### Address 
> f1fkh47gdwclmovclfz2kvorhhdofvgr5y7fjvkmi
#### Datacap Allocated
> 1.20PiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedyvkp2wxekl77dpdnyto6jylwp7ilr6a3qo7mobmnosm2o2xmksq

**Comment by cryptowhizzard** [comment]
checker:manualTrigger
